const cursos = [
  { id: "razonamiento", nombre: "Razonamiento lógico matemático", prerequisitos: [] },
  { id: "quimica", nombre: "Química", prerequisitos: [] },
  { id: "biocel", nombre: "Biología Celular", prerequisitos: [] },
  { id: "basesDisc", nombre: "Bases disciplinares para el cuidado de enfermería", prerequisitos: [] },
  { id: "comunicativas", nombre: "Taller de competencias comunicativas", prerequisitos: [] },
  { id: "aprendizaje", nombre: "Taller de competencias para el aprendizaje", prerequisitos: [] },
  { id: "perso1", nombre: "Taller de desarrollo personal 1", prerequisitos: [] },
  { id: "crecDes", nombre: "Crecimiento y desarrollo", prerequisitos: [] },
  { id: "bioquimica", nombre: "Bioquímica", prerequisitos: ["quimica", "biocel"] },
  { id: "fundAnat", nombre: "Fundamentos anatómicos para el cuidado", prerequisitos: [] },
  { id: "basesAPS", nombre: "Bases de Enfermería en APS", prerequisitos: ["basesDisc"] },
  { id: "auxilios", nombre: "Taller de primeros auxilios", prerequisitos: [] },
  { id: "perso2", nombre: "Taller de desarrollo personal 2", prerequisitos: [] },
  { id: "valores", nombre: "Cultura y valores", prerequisitos: [] },
  { id: "estadistica", nombre: "Estadísticas para ciencias de la salud", prerequisitos: [] },
  { id: "fisio", nombre: "Fisiología", prerequisitos: ["fundAnat"] },
  { id: "microbio", nombre: "Microbiología y parasitología clínica", prerequisitos: ["biocel"] },
  { id: "farmaco", nombre: "Farmacología", prerequisitos: ["bioquimica"] },
  { id: "fundPro", nombre: "Fundamentos del proceso de enfermería", prerequisitos: ["basesDisc", "fundAnat"] },
  { id: "sentido", nombre: "Persona y sentido", prerequisitos: [] },
  { id: "saludPub", nombre: "Fundamentos en salud pública", prerequisitos: ["estadistica"] },
  { id: "fisiopato", nombre: "Bases fisiopatológicas para el cuidado", prerequisitos: ["fisio"] },
  { id: "educaSalud", nombre: "Intervenciones educativas en salud", prerequisitos: [] },
  { id: "gestionSaludMental", nombre: "Gestión del cuidado en salud mental", prerequisitos: ["fundPro"] },
  { id: "procEnfer", nombre: "Proceso de enfermería", prerequisitos: ["fundPro"] },
  { id: "ingles1", nombre: "Inglés básico 1", prerequisitos: [] },
  { id: "gestionSalud", nombre: "Gestión en salud", prerequisitos: [] },
  { id: "gdcAdultoMayor", nombre: "Gestión del cuidado en adulto mayor", prerequisitos: ["fisiopato", "procEnfer", "gestionSaludMental"] },
  { id: "gdcFamilia", nombre: "Gestión del cuidado en la familia en APS", prerequisitos: ["fisiopato", "procEnfer", "gestionSaludMental"] },
  { id: "gdcHospMedico", nombre: "GDC en adulto y adulto mayor hospitalizado médico", prerequisitos: [] },
  { id: "ingles2", nombre: "Inglés básico 2", prerequisitos: ["ingles1"] },
  { id: "gestionCuidado", nombre: "Gestión del cuidado", prerequisitos: ["gestionSalud"] },
  { id: "gdcAPS", nombre: "GDC en adulto y adulto mayor en APS", prerequisitos: ["gdcAdultoMayor", "gdcFamilia"] },
  { id: "etica", nombre: "Ética en salud", prerequisitos: [] },
  { id: "gdcHospQuir", nombre: "GDC en adulto y adulto mayor hospitalizado quirúrgico", prerequisitos: [] },
  { id: "electivo1", nombre: "Electivo 1", prerequisitos: [] },
  { id: "metodologia", nombre: "Metodología de la investigación", prerequisitos: ["saludPub"] },
  { id: "cuidadosNino", nombre: "Fundamentos del cuidado en niño y adolescente hospitalizado", prerequisitos: ["gdcHospMedico", "gdcHospQuir"] },
  { id: "gestionNinoAPS", nombre: "Gestión del cuidado en niño y adolescente en APS", prerequisitos: ["gdcAPS"] },
  { id: "urgencias", nombre: "Fundamentos del cuidado en urgencias y desastres", prerequisitos: ["gdcHospMedico", "gdcHospQuir"] },
  { id: "electivo2", nombre: "Electivo 2", prerequisitos: [] },
  { id: "seminario", nombre: "Seminario de investigación", prerequisitos: ["metodologia"] },
  { id: "calidad", nombre: "Gestión de calidad y seguridad", prerequisitos: ["gestionCuidado"] },
  { id: "ninoHosp", nombre: "Gestión del cuidado en niño y adolescente hospitalizado", prerequisitos: ["cuidadosNino"] },
  { id: "promocion", nombre: "Promoción de la salud en organizaciones comunitarias", prerequisitos: ["gestionNinoAPS"] },
  { id: "urgencias2", nombre: "GDC en urgencias y desastres", prerequisitos: ["urgencias"] },
  { id: "electivo3", nombre: "Electivo 3", prerequisitos: [] },
  { id: "internado", nombre: "Internado", prerequisitos: ["razonamiento", "quimica", "biocel", "basesDisc", "comunicativas", "aprendizaje", "perso1", "crecDes", "bioquimica", "fundAnat", "basesAPS", "auxilios", "perso2", "valores", "estadistica", "fisio", "microbio", "farmaco", "fundPro", "sentido", "saludPub", "fisiopato", "educaSalud", "gestionSaludMental", "procEnfer", "ingles1", "gestionSalud", "gdcAdultoMayor", "gdcFamilia", "gdcHospMedico", "ingles2", "gestionCuidado", "gdcAPS", "etica", "gdcHospQuir", "electivo1", "metodologia", "cuidadosNino", "gestionNinoAPS", "urgencias", "electivo2", "seminario", "calidad", "ninoHosp", "promocion", "urgencias2", "electivo3"] }
];
